version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

jobs:
  nginx-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install gixy
          command: pip3 install gixy
      - run:
          name: Lint nginx configuration files
          command: yarn lint-nginx
  scss-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss
workflows:
  version: 2
  build:
    jobs:
      - nginx-lint
      - scss-lint
